CREATE DATABASE PAdmin
USE PAdmin
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Dutylog
	(
	id int NOT NULL IDENTITY (1, 1),
	date varchar(50) NULL,
	status int NULL,
	next_audit int NULL,
	weather int NULL,
	officer_main_give varchar(50) NULL,
	officer_sub_give varchar(50) NULL,
	note varchar(5000) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Dutylog ADD CONSTRAINT
	PK_Dutylog PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Dutylog SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dutylog SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Trans
	(
	id int NOT NULL IDENTITY (1, 1),
	item varchar(50) NULL,
	amount varchar(50) NULL,
	give tinyint NULL,
	recieve tinyint NULL,
	dutylog_id int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Trans ADD CONSTRAINT
	PK_Trans PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Trans ADD CONSTRAINT
	FK_Trans_Dutylog FOREIGN KEY
	(
	dutylog_id
	) REFERENCES dbo.Dutylog
	(
	id
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.Trans SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dutylog SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.inventory
	(
	id int NOT NULL IDENTITY (1, 1),
	title varchar(50) NULL,
	liaisonmorning varchar(50) NULL,
	liaisonevening varchar(50) NULL,
	dutylog_id int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.inventory ADD CONSTRAINT
	PK_inventory PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.inventory ADD CONSTRAINT
	FK_inventory_Dutylog FOREIGN KEY
	(
	dutylog_id
	) REFERENCES dbo.Dutylog
	(
	id
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.inventory SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.inventory SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.inventoryitems
	(
	id int NOT NULL IDENTITY (1, 1),
	item varchar(50) NULL,
	checking tinyint NULL,
	inventory_id int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.inventoryitems ADD CONSTRAINT
	PK_inventoryitems PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.inventoryitems ADD CONSTRAINT
	FK_inventoryitems_inventory FOREIGN KEY
	(
	inventory_id
	) REFERENCES dbo.inventory
	(
	id
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.inventoryitems SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dutylog SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.OTHER
	(
	id int NOT NULL IDENTITY (1, 1),
	title varchar(50) NULL,
	description varchar(250) NULL,
	remark varchar(250) NULL,
	dutylog_id int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.OTHER ADD CONSTRAINT
	PK_OTHER PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.OTHER ADD CONSTRAINT
	FK_OTHER_Dutylog FOREIGN KEY
	(
	dutylog_id
	) REFERENCES dbo.Dutylog
	(
	id
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.OTHER SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Dutylog SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Passinout
	(
	id int NOT NULL IDENTITY (1, 1),
	unit varchar(50) NULL,
	place varchar(50) NULL,
	firm_leader_name varchar(50) NULL,
	firm_leader_tel varchar(50) NULL,
	amount int NULL,
	works varchar(50) NULL,
	oversee_name varchar(50) NULL,
	oversee_tel varchar(50) NULL,
	remark varchar(250) NULL,
	dutylog_id int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Passinout ADD CONSTRAINT
	PK_Passinout PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Passinout ADD CONSTRAINT
	FK_Passinout_Dutylog FOREIGN KEY
	(
	dutylog_id
	) REFERENCES dbo.Dutylog
	(
	id
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.Passinout SET (LOCK_ESCALATION = TABLE)
GO
COMMIT