//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPOIDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dutylog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dutylog()
        {
            this.inventory = new HashSet<inventory>();
            this.OTHER = new HashSet<OTHER>();
            this.Passinout = new HashSet<Passinout>();
            this.Trans = new HashSet<Trans>();
        }
    
        public int id { get; set; }
        public string date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> next_audit { get; set; }
        public Nullable<int> weather { get; set; }
        public string officer_main_give { get; set; }
        public string officer_sub_give { get; set; }
        public string note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTHER> OTHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passinout> Passinout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trans> Trans { get; set; }
    }
}
